image: registry.art.rambler.ru/ruby/centos-base-ruby-nodejs-imagemagick:2.3.1-6x

.shared_tags: &shared_tags
  tags:
    - ci-official
    - docker

services:
  - postgres:9.5.3

cache:
  paths:
    - vendor/ruby

stages:
  - test

before_script:
  - bundle install -j$(nproc) --path vendor/ruby

rubocop:
  <<: *shared_tags

  script:
    - bundle exec rubocop

rspec:
  <<: *shared_tags

  stage: test

  variables:
    RAILS_ENV: test
    DATABASE_URL: postgres://postgres@postgres

  script:
    - bundle exec rake db:create
    - bundle exec rake db:schema:load
    - bundle exec rspec --tag ~integration
