FROM ruby:2.4.1-slim

RUN apt-get -qq update && apt-get install -qq -y --no-install-recommends \
  build-essential \
  libpq-dev \
  libmagickwand-dev \
  imagemagick \
  apt-utils \
  libxml2-dev \
  git

ENV APP /home/education
RUN mkdir -p $APP

WORKDIR $APP

COPY Gemfile Gemfile.lock ./

ENV BUNDLE_PATH /home/bundle
RUN bundle install

COPY . .
