version: '2'

services:
  qa-database:
    image: 'postgres:9.5.4'
    expose:
      - '5432'

  qa-service:
    image: 'rambler-qa-service-registry.art.rambler.ru/qa-service:latest'
    depends_on:
      - 'qa-database'
    environment:
      RAILS_ENV: 'test'
      DATABASE_URL: 'postgresql://qa-database'
      DATABASE_USERNAME: 'postgres'
    volumes:
      - './setup_qa_service.sh:/home/setup_qa_service.sh'
    expose:
      - '3001'
    command: 'bash /home/setup_qa_service.sh'

  database:
    image: 'postgres:9.5.4'
    expose:
      - '5432'

  education:
    depends_on:
      - 'qa-service'
      - 'database'
    build:
      context: '.'
      dockerfile: 'Dockerfile.test'
    command: 'bash test.sh'
    volumes:
      - '.:/home/education'
    environment:
      RAILS_ENV: 'test'
      DATABASE_URL: 'postgresql://database'
      DATABASE_USERNAME: 'postgres'
    env_file:
      - '.env.local'
