default_controllers: &default_controller
  complaints:
    index: true
    edit: true
    update: true
  dashboard:
    index: true
  employees:
    index: false
    new: false
    create: false
    edit: false
    update: false
    destroy: false
  metapages:
    index: true
    edit: true
    update: true
  seo:
    create: true
    update: true
    destroy: true
  seos_link:
    index: true
    create: true
    update: true
    destroy: true
  settings:
    edit: true
    update: true
  users:
    is_sentry: true
  versions:
    index: true
    show: true

superuser:
  controllers:
    <<: *default_controller
    employees:
      index: true
      new: true
      create: true
      edit: true
      update: true
      destroy: true

chief_editor:
  controllers:
    <<: *default_controller
    employees:
      index: true
      new: true
      create: true
      edit: true
      update: true
      destroy: true

editor:
  controllers:
    <<: *default_controller
    employees:
      index: false
      new: false
      create: false
      edit: false
      update: false
      destroy: false
    metapages:
      index: true
      edit: false
      update: false
    publishings:
      index: true
      new: false
      create: false
      edit: false
      update: false
      destroy: false
    settings:
      edit: false
      update: false
    users:
      is_sentry: false
    versions:
      index: false
      show: false
